### ISSUE TITLE
Links from other moodle sites

### ISSUE THREAD

**Issue by Manuelvaas** [JonasBernard/TU-Darmstadt-Moodle-Wrapper#2]
Would bei great, if you could add a small UI where you can add custom URLs from own moodle instances.

**Comment by JonasBernard** [comment]
Sorry, but as far as I know, it is impossible to add deep links to the app at runtime. So that function meant, I'd have to register all links that exsist as deep links and then dynamically either open moodle or the brwoser. In my opinion this is a little ugly and not what this app is ment for.

If you know how to build and install Android AKPs, you can fork this repository and edit the `app/src/main/AndroidManifest.xml` to match your URLs.
This should be not to hard to manage.
This article may also help you:
https://developer.android.com/training/app-links/deep-linking

If you want to install your self developed app along side with my version, you'll need to change the (so called) Application ID of the app. You have to change the atteibute `applicationId` under  `android { defaultConfig { applicationId [...] } }` in the file `app/build.gradle` to whatever you like. To make sure it is unique, it is typical to include one's own domain name. If you don't have one, get creative.

I hope, this helps.

**Comment by Manuelvaas** [comment]
Thank you very much, this helped me a lot, i have now a fork for my school on gitlab 👍
